"""empty message

Revision ID: 6267be5d6337
Revises: d387e15c7cae
Create Date: 2023-11-18 13:04:29.333238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6267be5d6337'
down_revision = 'd387e15c7cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
